global_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 5.0 #before: 5.0
  publish_frequency: 5.0 #before 0.5
  static_map: true
  transform_tolerance: 0.5
  cost_scaling_factor: 5 #50.0
  inflation_radius: 0.5 #0.4
