local_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 5.0 #before 5.0
  publish_frequency: 5.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05 #increase to for higher res 0.025
  transform_tolerance: 0.5 #0.5
  cost_scaling_factor: 5 #20
  inflation_radius: 0.3 #0.2

