TrajectoryPlannerROS:
  max_vel_x: +2.0
  min_vel_x: 0.0
  max_vel_theta: 2.5
  min_vel_theta: -2.5
  min_in_place_vel_theta: 1.0
  acc_lim_theta: 10.0
  acc_lim_x: 10.0
  acc_lim_y: 2.5
  acc_lim_trans: 10.0
  max_vel_trans: 10
  holonomic_robot: false


